### PR TITLE
Update to use Floe.register_scheme API

### PR DESCRIPTION
**Pull request by agrare**
Use the new interface added by https://github.com/ManageIQ/floe/pull/169

TODO:
- [x] release of floe with https://github.com/ManageIQ/floe/pull/169

### CODE REVIEW

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Just waiting on the floe release.

**Comment by Fryguy** [comment]
Actually - this PR should include the new Floe version bump

**Comment by agrare** [comment]
Yeah it is in the TODO above

**Comment by Fryguy** [comment]
Oh ok cool - I read that differently :+1:

**Comment by agrare** [comment]
@Fryguy okay released floe v0.11.0 and added that dependency to the gemspec here

**Pull request merged**
