### PR TITLE
Move workflow executing into manageiq-floe

### PR DESCRIPTION
**Pull request by agrare**
Depends on:
- [x] https://github.com/ManageIQ/floe/pull/33
- [x] https://github.com/ManageIQ/floe/pull/44

### CODE REVIEW

**Comment by agrare** [comment]
@miq-bot cross-repo-tests https://github.com/ManageIQ/manageiq/pull/22316 https://github.com/ManageIQ/floe/pull/44

**Comment by agrare** [comment]
@miq-bot cross-repo-tests ManageIQ/floe

**Comment by kbrock** [comment]
updated link, turned into checkbox.

that PR is closed. Does this have a different requirement?

**Comment by Fryguy** [comment]
There were a couple of PRs - I've updated the OP

@miq-bot cross-repo-tests ManageIQ/floe@master

**Comment by agrare** [comment]
@Fryguy yes that is correct

**Comment by agrare** [comment]
@kbrock can you review?  @Fryguy and I both have commits here now

**Review by kbrock — APPROVED** [review]
great job getting this logic out of here.

**Comment by Fryguy** [comment]
Backported to `petrosian` in commit 390b457ea3e686df82ae39eca049e0cd9880245f.

```text
commit 390b457ea3e686df82ae39eca049e0cd9880245f
Author: Keenan Brock <keenan@thebrocks.net>
Date:   Thu Jul 6 15:08:14 2023 -0400

    Merge pull request #5 from agrare/move_run_into_workflow
    
    Move workflow executing into manageiq-floe
    
    (cherry picked from commit 30e4673632438182bab375a6a0c05af9bb38e97c)
```

**Pull request merged**
